### ISSUE TITLE
Conduct: Git/GitHub workshop

### ISSUE THREAD

**Issue by kshitij10496** [kossiitkgp/internal-sessions#2]
## Abstract
Get everyone familiar with Git as a VCS and GitHub for collaboration.
Unlike our previous 3 hour long workshops, this will be a more hands-on session so as to 

**Speaker**: @pranitbauva1997 

#### Target Audience
- [x] Beginner (No programming background)
- [ ] Noob (Basic programming background, eg PDS)
- [ ] Intermediate (Elaborate in "Prerequisites" section)
- [ ] Advanced (Elaborate in "Prerequisites" section)

## Topic
> What topics will be covered in the workshop?
- What is a Version Control System?
- What is Git?
- Basic Git commands
  - `git add`
  - `git commit`
  - `git diff`
- Synchronisation with remotes
  - `git remote add`
  - `git fetch`
  - `git push`
- Branching
  - `git branch`
  - `git checkout`
- Opening PR on GitHub

## Prerequisites
OS: Linux, Mac (recommended for 
A system with Git installed on it.

Reference: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

## Duration
Session: 60 mins
Q/A: 10 mins

**Comment by thealphadollar** [comment]
Conducted successfully :+1:
