### ISSUE TITLE
Conduct: Web Engineering workshop

### ISSUE THREAD

**Issue by OrkoHunter** [kossiitkgp/internal-sessions#3]
## Abstract
Gettings people interested in Web development (Giving light to people who feel lost when they hear 'Frontend') 

#### Target Audience
- [ ] Beginner (No programming background)
- [x] Noob (Basic programming background, eg PDS)
- [ ] Intermediate (Elaborate in "Prerequisites" section)
- [ ] Advanced (Elaborate in "Prerequisites" section)

## Topic
1. You Don't Know CSS
 - Layouts (Display, float, blocks and other styling fundamentals)
 - CSS Selectors
 - Flexbox _(to rule them all!)_ 
2. React JS
 - How to create a powerful web app
3. Redux and Multiple page apps
 - Why Redux
 - JSX

## Resources

 - [Layouts](http://learnlayout.com/display.html)
   - Visualize [`float`](https://developer.mozilla.org/en-US/docs/Web/CSS/float)
 - [CSS Selectors](https://www.w3schools.com/cssref/css_selectors.asp)
   - [Specificity](https://www.w3.org/TR/selectors/#specificity)
   - [Exercises](https://flukeout.github.io/)
 - Flexbox
   - [Guide](https://bocoup.com/blog/dive-into-flexbox)
   - [Cheatsheet](https://yoksel.github.io/flex-cheatsheet/)
   - [Game](https://flexboxfroggy.com/)
 - ReactJS (Intermediate)
   - [Tutorial](https://reactjs.org/tutorial/tutorial.html)
   - [Quick Start](https://reactjs.org/docs/hello-world.html)
     - [React Create Project](https://github.com/facebook/create-react-app)
   - [Advance guides](https://reactjs.org/docs/jsx-in-depth.html)
   - [Todo App Exercise](https://codepen.io/kunukn/pen/akXRkX)
 - Redux (Not recommended for beginners)
   - [Short videos by the creator](https://egghead.io/courses/getting-started-with-redux)

Web Course - https://www.freecodecamp.org/map

## Duration
Duration: 2 hours
Q&A: 30 mins

## Suggestions

All of this content is too much and it is very hard to know everything. Suggested way to learn is by creating a lot of apps and practicing it properly.

For CSS, try to solve everything by flexbox. If not possible, go with other css tricks.

**Comment by sangeet259** [comment]
The flexbox froggy :frog: is the most amazing interactive learning tool I have used.
Thanks a lot @OrkoHunter

**Comment by thealphadollar** [comment]
Conducted successfully :+1:
